### PR TITLE
Use panels JSON input to add test codes and panel names

### PR DESCRIPTION
**Pull request by kjwinfield**
Example workbook, which has test codes and panel name and version data extracted from an input panel JSON
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`resources/home/dnanexus/make_workbook.py` line 368 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13#-O7-Eeag8vvzw5HWHiUv:-O7-Eeag8vvzw5HWHiUw:b-gu2g5z) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/536456ee5ff261af863d1f64b10aba48aca13abf/resources/home/dnanexus/make_workbook.py#L368)):*
> ```Python
>                     self.summary_content[(row, 3)] = panel_details.get(
>                         'panel_name'
>                     ) + f' ({panel_version})'
> ```

this can just be a single f string if you'd like instead of concatenating strings:
```
self.summary_content[(row, 3)] = (
    f"{panel_details.get('panel_name')} "
    f"({panel_version})"
)
```

also, do you need to check for `panel_name` and `rcode` exisitng so that they don't return `None` or will they always be present?



_Code quote:_
```Python
                    self.summary_content[(row, 3)] = panel_details.get(
                        'panel_name'
                    ) + f' ({panel_version})'
```
___
*[`resources/home/dnanexus/start_process.py` line 66 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13#-O7-FEboCNGH9ujis7RX:-O7-FEboCNGH9ujis7RY:b-h5bdb7) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/536456ee5ff261af863d1f64b10aba48aca13abf/resources/home/dnanexus/start_process.py#L66)):*
> ```Python
>             '--panels',
>             help='JSON file mapping panel ID to panel name and test code'
>         )
> ```

is this optional or always required?



_Code quote:_
```Python
        parser.add_argument(
            '--panels',
            help='JSON file mapping panel ID to panel name and test code'
        )
```

**Review by kjwinfield — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/make_workbook.py` line 368 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13#-O7-Eeag8vvzw5HWHiUv:-O7-Mvxw0WBV4XdtiHKQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/536456ee5ff261af863d1f64b10aba48aca13abf/resources/home/dnanexus/make_workbook.py#L368)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this can just be a single f string if you'd like instead of concatenating strings:
```
self.summary_content[(row, 3)] = (
    f"{panel_details.get('panel_name')} "
    f"({panel_version})"
)
```

also, do you need to check for `panel_name` and `rcode` exisitng so that they don't return `None` or will they always be present?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/start_process.py` line 66 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13#-O7-FEboCNGH9ujis7RX:-O7-Mx4MA9lmN8qLC9cW:bc1nlno) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/536456ee5ff261af863d1f64b10aba48aca13abf/resources/home/dnanexus/start_process.py#L66)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this optional or always required?
</blockquote></details>

Done. 
it is optional, added line to bash script to add it if present in the inputs

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13)* status: 1 of 4 files reviewed, 1 unresolved discussion

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/13)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)

**Pull request merged**
